# Generated by Django 4.2.4 on 2023-08-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionesTransformadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codificacion', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('nivelTension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTelecontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_tension', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('gabinete', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('mask', models.CharField(max_length=50)),
                ('defGw', models.CharField(max_length=50)),
                ('estacionTransformadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.estacionestransformadoras')),
            ],
            options={
                'verbose_name': 'Equipo de Telecontrol',
                'verbose_name_plural': 'Equipos de Telecontrol',
            },
        ),
        migrations.CreateModel(
            name='EquipoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_tension', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('gabinete', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('mask', models.CharField(max_length=50)),
                ('defGw', models.CharField(max_length=50)),
                ('estacionTransformadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.estacionestransformadoras')),
            ],
            options={
                'verbose_name': 'Equipo de Red',
                'verbose_name_plural': 'Equipos de Red',
            },
        ),
        migrations.CreateModel(
            name='EquipoProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_tension', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('gabinete', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('mask', models.CharField(max_length=50)),
                ('defGw', models.CharField(max_length=50)),
                ('estacionTransformadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.estacionestransformadoras')),
            ],
            options={
                'verbose_name': 'Equipo de Protección',
                'verbose_name_plural': 'Equipos de Proteccion',
            },
        ),
    ]
