# Generated by Django 4.2.4 on 2023-08-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacionestransformadoras',
            options={'verbose_name': 'Estación Transformadora', 'verbose_name_plural': 'Estaciones Transformadoras'},
        ),
    ]
